"""Adicionar coluna hash_id e outras alterações

Revision ID: 41e0dc9232f0
Revises: 64f6624777fe
Create Date: 2025-05-27 21:16:04.302293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e0dc9232f0'
down_revision = '64f6624777fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_hash', sa.String(length=64), nullable=False))
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=18),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_acoes_user_hash'), ['user_hash'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_hash'], ['hash_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('negociacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_hash', sa.String(length=64), nullable=False))
        batch_op.alter_column('tipo_movimentacao',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('preco',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('corretagem',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_negociacoes_user_hash'), ['user_hash'], unique=False)
        batch_op.create_unique_constraint('uix_negociacao_completa', ['data_negocio', 'tipo_movimentacao', 'mercado', 'instituicao', 'acao_id', 'quantidade', 'preco', 'valor', 'user_hash'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_hash'], ['hash_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_hash', sa.String(length=64), nullable=False))
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_relatorios_user_hash'), ['user_hash'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_hash'], ['hash_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('saldos_precos_medios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_hash', sa.String(length=64), nullable=False))
        batch_op.alter_column('preco_medio',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_saldos_precos_medios_user_hash'), ['user_hash'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_hash'], ['hash_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_hash_id'), ['hash_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_hash_id'))
        batch_op.drop_column('hash_id')

    with op.batch_alter_table('saldos_precos_medios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_saldos_precos_medios_user_hash'))
        batch_op.alter_column('preco_medio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('user_hash')

    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_relatorios_user_hash'))
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('user_hash')

    with op.batch_alter_table('negociacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uix_negociacao_completa', type_='unique')
        batch_op.drop_index(batch_op.f('ix_negociacoes_user_hash'))
        batch_op.alter_column('corretagem',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tipo_movimentacao',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('user_hash')

    with op.batch_alter_table('acoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_acoes_user_hash'))
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('user_hash')

    # ### end Alembic commands ###
