"""Migração inicial automática

Revision ID: 64f6624777fe
Revises: 
Create Date: 2025-05-25 21:19:27.285917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f6624777fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=100), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_negocio', sa.Date(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=20), nullable=False),
    sa.Column('mercado', sa.String(length=50), nullable=False),
    sa.Column('prazo_vencimento', sa.String(length=50), nullable=False),
    sa.Column('instituicao', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('corretagem', sa.Float(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldos_precos_medios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_base', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_medio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acao_id', 'data_base', name='uix_acao_data_base')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_precos_medios')
    op.drop_table('negociacoes')
    op.drop_table('relatorios')
    op.drop_table('acoes')
    op.drop_table('users')
    # ### end Alembic commands ###
